export const font = {
  RobotoMono: 'Roboto-Mono',
  Sans: 'Product-Sans',
  RobotoRegular: 'Roboto-Regular',
};

export const color = {
  lightMode: {
    buttonBorder: 'black',
    buttonText: 'black',
    emailBackground: '#FB1C1C1A',
    emailBorder: '#D41B1B',
    headerBackground: '#FAF4F2',
    hintText: '#757575',
    homeBackground: '#FAF4F2',
    resultBackground: 'white',
    resultFooter: '#FAF4F2',
    rewriteButton: '#FFE7AB',
    shadow: 'black',
    summarizeButton: '#D1EDBF',
    homeSvg: '#7986cb',
    resultSvg: '#666666',
    text: 'black',
    textBackground: 'white',
    tweetBackground: '#03A9F41A',
    tweetBorder: '#03A9F4',
  },
  darkMode: {
    buttonBorder: 'black',
    buttonText: 'black',
    emailBackground: '#FB1C1C1A',
    emailBorder: '#D41B1B',
    headerBackground: '#FAF4F2',
    hintText: '',
    homeBackground: '#212121',
    resultBackground: '#212121',
    resultFooter: '#FAF4F2',
    rewriteButton: '#FFE7AB',
    shadow: 'black',
    summarizeButton: '#D1EDBF',
    homeSvg: '#7986cb',
    resultSvg: '#666666',
    text: 'white',
    textBackground: 'black',
    tweetBackground: '#03A9F41A',
    tweetBorder: '#03A9F4',
  },
};
